apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: "./infrastructure-local/monitoring/grafana"
  prune: false
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-config