apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-stack
  namespace: flux-system
spec:
  dependsOn:
    - name: alloy
      namespace: flux-system  
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: "./infrastructure-local/monitoring/prometheus"
  prune: true
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-config