apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  labels:
    app.kubernetes.io/component: loki
    kustomize.toolkit.fluxcd.io/substitute: disabled
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
data:
  config.yaml: |-
    auth_enabled: false

    # -- Check https://grafana.com/docs/loki/latest/configuration/#server for more info on the server configuration.
    server:
      http_listen_port: 3100
      grpc_listen_port: 9095
      http_server_read_timeout: 300s
      http_server_write_timeout: 300s

    memberlist:
      abort_if_cluster_join_fails: false
      bind_port: 7946
      max_join_backoff: 1m
      max_join_retries: 10
      min_join_backoff: 1s
      join_members:
      - loki-memberlist.monitoring.svc.cluster.local:7946

    schema_config:
      configs:
      - from: "2023-10-14"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: index_
          period: 24h

    # -- Limits config
    limits_config:
      ingestion_rate_mb: 50
      ingestion_burst_size_mb: 75
      max_global_streams_per_user: 15000
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      max_cache_freshness_per_query: 10m
      split_queries_by_interval: 15m
      per_stream_rate_limit: 5MB
      per_stream_rate_limit_burst: 20MB
      max_query_lookback: 720h
      max_query_length: 72h
      retention_period: 744h
      query_timeout: 5m

    # -- Additional storage config
    storage_config:
      hedging:
        at: "250ms"
        max_per_second: 20
        up_to: 3
      tsdb_shipper:
        active_index_directory: /var/loki/data/tsdb-index
        cache_location: /var/loki/data/tsdb-cache
        cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space

      # --  Optional compactor configuration
    compactor:
      working_directory: /var/loki/data/retention
      compaction_interval: 5m
      retention_enabled: true
      retention_delete_delay: 2h
      retention_delete_worker_count: 150
      delete_request_store: s3

    ingester:
      autoforget_unhealthy: false
      chunk_encoding: snappy
      wal:
        flush_on_shutdown: true

    # -- Check https://grafana.com/docs/loki/latest/configuration/#common_config for more info on how to provide a common configuration
    common:
      path_prefix: /var/loki
      replication_factor: 1
      compactor_address: loki-backend

      storage:
        s3:
          endpoint: ${S3_ENDPOINT}
          region: ${S3_REGION}
          bucketnames: ${S3_BUCKET}
          access_key_id: ${S3_ACCESSKEY}
          secret_access_key: ${S3_SECRETKEY}
          insecure: true
          http_config:
            idle_conn_timeout: 90s
            response_header_timeout: 0s
            insecure_skip_verify: false
          s3forcepathstyle: true

      ring:
        kvstore:
          store: memberlist

    querier:
      max_concurrent: 16

    query_scheduler:
      max_outstanding_requests_per_tenant: 32768

    query_range:
      parallelise_shardable_queries: true
      align_queries_with_step: true
      max_retries: 5
      cache_results: true
      results_cache:
        cache:
          embedded_cache:
            enabled: true

    ruler:
      storage:
        s3:
          bucketnames: lokilogs

    analytics:
      reporting_enabled: false

