apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: loki-stack
    app.kubernetes.io/component: loki
    grafana_datasource: "1"
  name: loki-datasource
  namespace: monitoring
data:
  loki-stack-datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      access: proxy
      url: "http://loki-gateway.monitoring.svc.cluster.local"
      version: 1
      isDefault: false
      jsonData:
        {}
