apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  labels:
    grafana_datasource: "1"
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Alertmanager
        type: alertmanager
        url: http://prometheus-stack-kube-prom-alertmanager.monitoring.svc.cluster.local:9093
        access: proxy
        jsonData:
          # Valid options for implementation include mimir, cortex and prometheus
          implementation: prometheus
          # Whether or not Grafana should send alert instances to this Alertmanager
          handleGrafanaManagedAlerts: false
        # optionally
        basicAuth: false
        #basicAuthUser: my_user
        #secureJsonData:
        #  basicAuthPassword: test_password