apiVersion: v1
kind: ConfigMap
metadata:
  name: mimir-datasource
  labels:
    grafana_datasource: "1"
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: prometheus
        url: http://prometheus-operated.monitoring:9090
        access: proxy
        isDefault: true
        jsonData:
          timeInterval: 1m
          exemplarTraceIdDestinations:
            - datasourceUid: tempo
              name: traceID
          httpMethod: POST
        # optionally
        basicAuth: false
        #basicAuthUser: my_user
        #secureJsonData:
        #  basicAuthPassword: test_password
        editable: true
      - name: FlaggerPrometheus
        type: prometheus
        uid: flaggerprometheus
        url: http://flagger-prometheus.istio-system:9090
        access: proxy
        isDefault: false
        jsonData:
          timeInterval: 1m
          exemplarTraceIdDestinations:
            - datasourceUid: tempo
              name: traceID
          httpMethod: POST
        # optionally
        basicAuth: false
        #basicAuthUser: my_user
        #secureJsonData:
        #  basicAuthPassword: test_password
        editable: true
      - name: Loki
        type: loki
        uid: loki
        url: http://loki-gateway.monitoring.svc.cluster.local
        access: proxy
        isDefault: false
        jsonData:
          derivedFields:
          - datasourceUid: tempo
            matcherRegex: "^.*?traceI[d|D]=(\\w+).*$"
            name: traceID
            url: '$${__value.raw}'
        # optionally
        basicAuth: false
        editable: true
      