image:
  tag: 12.0.2
# for high availability
headlessService: true

#envFromSecret: "grafana-auth-secret"

grafana.ini:
  server:
    domain: "{{ if (and .Values.ingress.enabled .Values.ingress.hosts) }}{{ .Values.ingress.hosts | first }}{{ else }}''{{ end }}"
    root_url: https://grafana.cloudland.com
  paths:
    data: /var/lib/grafana/
    logs: /var/log/grafana
    plugins: /var/lib/grafana/plugins
    provisioning: /etc/grafana/provisioning
  analytics:
    check_for_updates: false
  log:
    mode: console
  grafana_net:
    url: https://grafana.net

ingress:
  enabled: false
  
#service:
#  enabled: true
#  type: LoadBalancer
persistence:
  type: pvc
  enabled: true
#  storageClassName: oci
  accessModes:
    - ReadWriteOnce
  size: 5Gi
sidecar:
  alerts:
    enabled: true
    labelValue: "1"
  datasources:
    enabled: true
    labelValue: "1"
  dashboards: 
    enabled: true
    labelValue: "1" 
#extraVolumeMounts:
#- mountPath: /etc/grafana/provisioning/alerting
#  name: grafana-alerting
#  readOnly: false
#extraContainerVolumes:
#- name: grafana-alerting
#  configMap:
#    defaultMode: 420
#    name: grafana-alerting
adminUser: admin
adminPassword: cloudland