apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-alloy
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: alloy
      sourceRef:
        kind: HelmRepository
        name: loki
        namespace: flux-system
      interval: 1m
  valuesFrom:
  - kind: ConfigMap
    name: values-alloy