apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  labels:
    grafana_datasource: "1"
data:
  datasourcedelete.yaml: |-
    apiVersion: 1
    deleteDatasources:
    - name: Mimir
      orgId: 1
