apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helmrelease-grafana.yaml
- grafana-datasource.yaml
- grafana-alerting-config.yaml

namespace: monitoring

configMapGenerator:
- name: values-grafana
  files:
  - values.yaml=grafana-values.yaml
  options:
    disableNameSuffixHash: true
