apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: slixmonitoring
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-stack
        namespace: flux-system
      interval: 1m
  valuesFrom:
  - kind: ConfigMap
    name: values-prometheus-stack
    