apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helmrelease-prometheus.yaml
#- grafana-alerting-config.yaml
#- grafana-alerting.yaml
#- grafana-datasource-alertmanager.yaml

namespace: monitoring

configMapGenerator:
- name: values-prometheus-stack
  files:
  - values.yaml=prometheus-stack-values.yaml
  options:
    disableNameSuffixHash: true