apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mimir
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: mimir-distributed
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 1m
  valuesFrom:
  - kind: ConfigMap
    name: values-mimir
  #dependsOn:
  #- name: slixmonitoring
  #  namespace: monitoring
  