apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helmrelease-mimir.yaml
#- loki-config.yaml
- mimir-datasource.yaml

namespace: monitoring

configMapGenerator:
- name: values-mimir
  files:
  - values.yaml=mimir-values.yaml
  options:
    disableNameSuffixHash: true
    labels:
      gvhcfmvkustomize.toolkit.fluxcd.io/substitute: disabled
    annotations:
      kustomize.toolkit.fluxcd.io/substitute: disabled