apiVersion: v1
kind: Secret
metadata:
  name: mimir-config
  labels:
    app.kubernetes.io/component: loki
stringData:
  config.yaml: |-
    auth_enabled: false

    # -- Check https://grafana.com/docs/loki/latest/configuration/#server for more info on the server configuration.
    server:
      http_listen_port: 3100
      grpc_listen_port: 9095
      http_server_read_timeout: 300s
      http_server_write_timeout: 300s

    memberlist:
      abort_if_cluster_join_fails: false
      bind_port: 7946
      max_join_backoff: 1m
      max_join_retries: 10
      min_join_backoff: 1s
      join_members:
      - loki-memberlist.monitoring.svc.cluster.local:7946

    schema_config:
      configs:
      - from: "2020-10-24"
        store: boltdb-shipper
        object_store: s3
        schema: v12
        index:
          prefix: index_
          period: 24h

    # -- Limits config
    limits_config:
      enforce_metric_name: false
      ingestion_rate_mb: 50
      ingestion_burst_size_mb: 75
      max_global_streams_per_user: 15000
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      max_cache_freshness_per_query: 10m
      split_queries_by_interval: 15m
      per_stream_rate_limit: 5MB
      per_stream_rate_limit_burst: 20MB
      max_query_lookback: 720h
      max_query_length: 72h
      retention_period: 744h
      query_timeout: 5m

    # -- Additional storage config
    storage_config:
      hedging:
        at: "250ms"
        max_per_second: 20
        up_to: 3
      boltdb_shipper:
        active_index_directory: /var/loki/data/index
        cache_location: /var/loki/data/boltdb-cache
        cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
        shared_store: s3

      # --  Optional compactor configuration
    compactor:
      working_directory: /var/loki/data/retention
      shared_store: s3
      compaction_interval: 5m
      retention_enabled: true
      retention_delete_delay: 2h
      retention_delete_worker_count: 150

    ingester:
      autoforget_unhealthy: true
      chunk_encoding: snappy
      wal:
        flush_on_shutdown: true

    # -- Check https://grafana.com/docs/loki/latest/configuration/#common_config for more info on how to provide a common configuration
    common:
      path_prefix: /var/loki
      replication_factor: 2
      compactor_address: loki-backend

      storage:
        s3:
          endpoint: frsjez6mlvwx.compat.objectstorage.eu-frankfurt-1.oraclecloud.com
          region: eu-frankfurt-1
          bucketnames: lokilogging
          access_key_id: 0d959e08681346c1cb269536a1a55dc7cee5ae69
          secret_access_key: t8ii3vcF3OdCz3zuU9XiyYnHh6Aq7qW5ColW3S9uzLU=
          insecure: false
          sse_encryption: false
          http_config:
            idle_conn_timeout: 90s
            response_header_timeout: 0s
            insecure_skip_verify: false
          s3forcepathstyle: true

      ring:
        kvstore:
          store: memberlist

    querier:
      max_concurrent: 100
      engine:
        timeout: 5m0s

    query_scheduler:
      max_outstanding_requests_per_tenant: 2048

    query_range:
      parallelise_shardable_queries: true
      align_queries_with_step: true
      max_retries: 5
      cache_results: true
      results_cache:
        cache:
          embedded_cache:
            enabled: true

    ruler:
      storage:
        s3:
          bucketnames: lokilogging

    analytics:
      reporting_enabled: false

