apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: flagger
  namespace: istio-system
spec:
  interval: 1h0m0s
  url: https://flagger.app
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flagger
  namespace: istio-system
spec:
  releaseName: flagger
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: flagger
      sourceRef:
        kind: HelmRepository
        name: flagger
  interval: 1h0m0s
  values:
    meshProvider: istio
    metricsServer: http://prometheus-operated.monitoring:9090
    prometheus:
      install: false
    serviceMonitor:
      enabled: false
      honorLabels: false
      labels: 
        release: slixmonitoring

# ---
# apiVersion: helm.toolkit.fluxcd.io/v2
# kind: HelmRelease
# metadata:
#   name: flagger-grafana
#   namespace: istio-system
# spec:
#   chart:
#     spec:
#       chart: grafana
#       sourceRef:
#         kind: HelmRepository
#         name: flagger
#   interval: 1h0m0s
#   releaseName: flagger-grafana
#   values:
#     url: http://flagger-prometheus.istio-system:9090
#     image:
#       tag: 10.4.4
