apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helmrelease-loki.yaml
- loki-config.yaml
- loki-datasource.yaml

namespace: monitoring

configMapGenerator:
- name: values-loki
  files:
  - values.yaml=loki-values.yaml
  options:
    disableNameSuffixHash: true
